// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8nNcThCrTh81kQd5u2XZ1HHBuO6Moung',
    appId: '1:143769547639:web:6b9d3b14ddf45ec4f66772',
    messagingSenderId: '143769547639',
    projectId: 'doctor-directory-1d25b',
    authDomain: 'doctor-directory-1d25b.firebaseapp.com',
    storageBucket: 'doctor-directory-1d25b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZUfbIp-0liVsMTaYmvUrTMYACx8xoRNo',
    appId: '1:143769547639:android:78a752f730af7beaf66772',
    messagingSenderId: '143769547639',
    projectId: 'doctor-directory-1d25b',
    storageBucket: 'doctor-directory-1d25b.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8nNcThCrTh81kQd5u2XZ1HHBuO6Moung',
    appId: '1:143769547639:web:06919f6ccd9157a9f66772',
    messagingSenderId: '143769547639',
    projectId: 'doctor-directory-1d25b',
    authDomain: 'doctor-directory-1d25b.firebaseapp.com',
    storageBucket: 'doctor-directory-1d25b.firebasestorage.app',
  );
}
